package com.sartor.fruitdiet.api;

import com.sartor.fruitdiet.api.data.Fruit;
import com.sartor.fruitdiet.api.data.NutritionalData;

public class Fruits {

    public static final Fruit BANANA = Fruit.builder()
            .name("Banana")
            .family("Musaceae")
            .order("Zingiberales")
            .genus("Musa")
            .nutritionalData(NutritionalData.builder()
                    .carbohydrates(22.0)
                    .protein(1.0)
                    .fat(0.2)
                    .calories(96)
                    .sugar(17.2)
                    .build()
            )
            .build();
    public static final Fruit RASPBERRY = Fruit.builder()
            .name("Raspberry")
            .family("Rosaceae")
            .order("Rosales")
            .genus("Rubus")
            .nutritionalData(NutritionalData.builder()
                    .carbohydrates(12.0)
                    .protein(1.2)
                    .fat(0.7)
                    .calories(53)
                    .sugar(4.4)
                    .build()
            )
            .build();
    public static final Fruit DURIAN = Fruit.builder()
            .name("Durian")
            .family("Malvaceae")
            .order("Malvales")
            .genus("Durio")
            .nutritionalData(NutritionalData.builder()
                    .carbohydrates(27.1)
                    .protein(1.5)
                    .fat(5.3)
                    .calories(147)
                    .sugar(6.75)
                    .build()
            )
            .build();
    public static final Fruit WATERMELON = Fruit.builder()
            .name("Watermelon")
            .family("Cucurbitaceae")
            .order("Cucurbitales")
            .genus("Citrullus")
            .nutritionalData(NutritionalData.builder()
                    .carbohydrates(8.0)
                    .protein(0.6)
                    .fat(0.2)
                    .calories(30)
                    .sugar(6.0)
                    .build()
            )
            .build();
    public static final Fruit APPLE = Fruit.builder()
            .name("Apple")
            .family("Rosaceae")
            .order("Rosales")
            .genus("Malus")
            .nutritionalData(NutritionalData.builder()
                    .carbohydrates(11.4)
                    .protein(0.3)
                    .fat(0.4)
                    .calories(52)
                    .sugar(10.3)
                    .build()
            )
            .build();
    public static final Fruit PEAR = Fruit.builder()
            .name("Pear")
            .family("Rosaceae")
            .order("Rosales")
            .genus("Pyrus")
            .nutritionalData(NutritionalData.builder()
                    .carbohydrates(15.0)
                    .protein(0.4)
                    .fat(0.1)
                    .calories(57)
                    .sugar(10.0)
                    .build()
            )
            .build();

}
